export enum QualificationType {
  //COMUNICAÇÃO
  COMMUNICATION = 'CO',

  //ALIMENTAÇÃO
  FOOD = 'AL',

  //HABILIDADES SOCIAIS
  SOCIAL_SKILLS = 'HS',

  //COMPORTAMENTO
  BEHAVIOR = 'CP',

  //AUTONOMIA E AUTOREGULÃO
  AUTONOMY_SELF_REGULATION = 'AA',

  //HABILIDADES MOTORAS E PRÁXICAS
  MOTOR_PRACTICAL_SKILLS = 'HM',

  //HABILIDADES ACADÊMICAS
  ACADEMIC_SKILLS = 'HA',
}
